### ISSUE TITLE
Auto Signout

### ISSUE THREAD

**Issue by Shepherdwhen** [WerewolvesRevamped/Werewolves-Bot#46]
Add an auto Signout feature for people who leave the server

**Comment by McTsts** [comment]
Done
![image](https://github.com/user-attachments/assets/13cfaaf2-836e-4ec1-a945-dc431812f722)

It now auto signouts in signup phase, auto signouts and pings in setup and kills and pings ingame. It also now runs checks of whether the player actually is signed up / alive before doing those actions instead of just always attempting to kill them
